[package]
name = "libr"
version = "0.1.0"
edition = "2024"

# Crate fuori dal workspace del kernel: build freestanding separata.
[workspace]

[dependencies]
syscall-numbers = { path = "../../syscall-numbers" }
arcafs = { path = "../../arcafs" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
